CREATE TABLE "CLIENTE" (
    "IDCLIENTE" INTEGER not null primary key,
    "NOMBRE" VARCHAR(50),
    "TELEFONO" VARCHAR(30),
    "CORREO" VARCHAR(10)
);

CREATE TABLE "EMPLEADO" (
    "IDEMPLEADO" INTEGER not null primary key,
    "NOMBRE" VARCHAR(50),
    "TELEFONO" VARCHAR(30),
    "CORREO" VARCHAR(100),
    "SALARIO" DOUBLE
);


CREATE TABLE "PRODUCTO" (
    "IDPRODUCTO" INTEGER not null primary key,
    "NOMBRE" VARCHAR(50),
    "DESCRIPCION" VARCHAR(30),
    "TALLA" VARCHAR(10),
    "CANTIDAD" INTEGER,
    "PRECIOCOMPRA" DOUBLE,
    "PRECIOVENTA" DOUBLE
);

CREATE TABLE "ENCABEZADOFACTURA" (
    "IDENCABEZADOFACTURA" INTEGER not null primary key,
    "IDCLIENTE" INTEGER,
    "IDEMPLEADO" INTEGER,
    "VALORVENTA" double,
    "DESCUENTO" double,
    "SUBTOTAL" double,
    "IVA" double,
    "TOTALVENTA" double
);

CREATE TABLE "DETALLEFACTURA" (
    "IDETALLEFACTURA" INTEGER not null primary key,
    "IDENCABEZADOFACTURA" INTEGER,
    "IDPRODUCTO" INTEGER,
    "DESCRIPCIONPRODUCTO" varchar(50),
    "CANTIDAD" double,
    "PRECIO" double,
    "TOTAL" double
);

ALTER TABLE DETALLEFACTURA
ADD FOREIGN KEY (IDPRODUCTO) 
REFERENCES PRODUCTO(IDPRODUCTO);

ALTER TABLE DETALLEFACTURA
ADD FOREIGN KEY (IDENCABEZADOFACTURA) 
REFERENCES ENCABEZADOFACTURA(IDENCABEZADOFACTURA);

ALTER TABLE ENCABEZADOFACTURA
ADD FOREIGN KEY (IDCLIENTE) 
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE ENCABEZADOFACTURA
ADD FOREIGN KEY (IDEMPLEADO) 
REFERENCES EMPLEADO(IDEMPLEADO);
